2018-06-17 22:14:23,989  * Running on https://0.0.0.0:8443/ (Press CTRL+C to quit)
2018-06-17 22:14:32,033 CARD LOADED: 16rd000 was touched.
2018-06-17 22:14:32,045 127.0.0.1 - - [17/Jun/2018 22:14:32] "POST /id_check HTTP/1.1" 201 -
2018-06-17 22:14:34,125 LOGIN: 16rd000 loged in.
2018-06-17 22:14:34,155 127.0.0.1 - - [17/Jun/2018 22:14:34] "POST /pw_check HTTP/1.1" 201 -
2018-06-17 22:14:36,486 LOGOUT: 16rd000 logged out.
2018-06-17 22:14:36,503 127.0.0.1 - - [17/Jun/2018 22:14:36] "POST /id_check HTTP/1.1" 201 -
2018-06-18 00:27:09,641  * Running on https://0.0.0.0:8443/ (Press CTRL+C to quit)
2018-06-18 00:28:44,505  * Running on https://0.0.0.0:8443/ (Press CTRL+C to quit)
2018-06-18 00:29:51,128 Exception on /register [POST]
Traceback (most recent call last):
  File "/home/natsuki/.pyenv/versions/3.6.5/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/natsuki/.pyenv/versions/3.6.5/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/natsuki/.pyenv/versions/3.6.5/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/natsuki/.pyenv/versions/3.6.5/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/natsuki/.pyenv/versions/3.6.5/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/natsuki/.pyenv/versions/3.6.5/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 120, in register
    cur.execute('insert into usr_table values(\''+Student_id+'\',\''+pw+'\',0)')
sqlite3.OperationalError: table usr_table has 4 columns but 3 values were supplied
2018-06-18 00:29:51,132 127.0.0.1 - - [18/Jun/2018 00:29:51] "POST /register HTTP/1.1" 500 -
2018-06-18 00:31:52,400  * Running on https://0.0.0.0:8443/ (Press CTRL+C to quit)
2018-06-18 00:31:55,989 REGISTER: test registered
2018-06-18 00:31:55,992 127.0.0.1 - - [18/Jun/2018 00:31:55] "POST /register HTTP/1.1" 201 -
2018-06-18 00:32:29,823 127.0.0.1 - - [18/Jun/2018 00:32:29] "GET /db_operation HTTP/1.1" 200 -
2018-06-18 00:32:30,434 127.0.0.1 - - [18/Jun/2018 00:32:30] "GET /favicon.ico HTTP/1.1" 404 -
2018-06-18 00:32:31,920 127.0.0.1 - - [18/Jun/2018 00:32:31] "GET /db_operation/print HTTP/1.1" 200 -
2018-06-18 00:39:37,178  * Running on https://0.0.0.0:8443/ (Press CTRL+C to quit)
2018-06-18 00:39:42,476 Exception on /register [POST]
Traceback (most recent call last):
  File "/home/natsuki/.pyenv/versions/3.6.5/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/natsuki/.pyenv/versions/3.6.5/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/natsuki/.pyenv/versions/3.6.5/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/natsuki/.pyenv/versions/3.6.5/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/natsuki/.pyenv/versions/3.6.5/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/natsuki/.pyenv/versions/3.6.5/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 120, in register
    cur.execute('insert into usr_table values(\''+Student_id+'\',\''+pw+'\',0,"")')
sqlite3.IntegrityError: UNIQUE constraint failed: usr_table.Student_id
2018-06-18 00:39:42,479 127.0.0.1 - - [18/Jun/2018 00:39:42] "POST /register HTTP/1.1" 500 -
2018-06-18 00:40:42,102  * Running on https://0.0.0.0:8443/ (Press CTRL+C to quit)
2018-06-18 00:44:57,962  * Running on https://0.0.0.0:8443/ (Press CTRL+C to quit)
2018-06-18 00:45:04,485 REGISTER ERROR: maybe UNIQUE
2018-06-18 00:45:04,485 127.0.0.1 - - [18/Jun/2018 00:45:04] "POST /register HTTP/1.1" 403 -
2018-06-18 00:45:25,754  * Running on https://0.0.0.0:8443/ (Press CTRL+C to quit)
2018-06-18 00:46:44,398  * Running on https://0.0.0.0:8443/ (Press CTRL+C to quit)
2018-06-18 00:46:46,603 REGISTER ERROR: maybe UNIQUE
2018-06-18 00:46:46,604 127.0.0.1 - - [18/Jun/2018 00:46:46] "POST /register HTTP/1.1" 403 -
2018-06-18 00:46:51,160 REGISTER ERROR: maybe UNIQUE
2018-06-18 00:46:51,161 127.0.0.1 - - [18/Jun/2018 00:46:51] "POST /register HTTP/1.1" 403 -
2018-06-18 00:47:26,323 REGISTER: CASHMERE registered
2018-06-18 00:47:26,325 127.0.0.1 - - [18/Jun/2018 00:47:26] "POST /register HTTP/1.1" 201 -
2018-06-18 00:47:54,484  * Running on https://0.0.0.0:8443/ (Press CTRL+C to quit)
2018-06-18 00:48:03,024 CARD LOADED: 16rd000 was touched.
2018-06-18 00:48:03,036 127.0.0.1 - - [18/Jun/2018 00:48:03] "POST /id_check HTTP/1.1" 201 -
2018-06-18 00:48:28,073 127.0.0.1 - - [18/Jun/2018 00:48:28] "POST /pw_check HTTP/1.1" 403 -
2018-06-18 00:48:39,845 LOGIN: 16rd000 loged in.
2018-06-18 00:48:39,858 127.0.0.1 - - [18/Jun/2018 00:48:39] "POST /pw_check HTTP/1.1" 201 -
2018-06-18 00:48:45,729 127.0.0.1 - - [18/Jun/2018 00:48:45] "GET /db_operation/print HTTP/1.1" 200 -
2018-06-18 00:48:52,082 127.0.0.1 - - [18/Jun/2018 00:48:52] "GET /db_operation? HTTP/1.1" 200 -
2018-06-18 00:48:52,949 127.0.0.1 - - [18/Jun/2018 00:48:52] "GET /db_operation/print HTTP/1.1" 200 -
